export const CHAPTERS: Record<string, string[]> = {
  "Australian Mathematics Competition (AMC)": [
    "Number & Arithmetic",
    "Algebra & Equations",
    "Geometry & Measurement",
    "Counting & Combinatorics",
    "Probability & Statistics",
    "Patterns & Sequences",
    "Logic & Problem Solving",
    "Speed, Rates & Ratios",
  ],
  "Maths Olympiad": [
    "Number Theory & Divisibility",
    "Algebraic Manipulation",
    "Euclidean Geometry",
    "Combinatorics & Counting",
    "Inequalities",
    "Sequences & Series",
    "Proof Techniques",
  ],
  "ACER Exam": [
    "Reading Comprehension",
    "Mathematical Reasoning",
    "Quantitative Problem Solving",
    "Abstract & Non-verbal Reasoning",
    "Verbal Reasoning & Vocabulary",
    "Written Expression",
  ],
  "ICAS": [
    "Reading & Comprehension",
    "Spelling & Vocabulary",
    "Grammar & Punctuation",
    "Number & Arithmetic",
    "Algebra, Patterns & Geometry",
    "Measurement, Data & Chance",
    "Science Inquiry & Reasoning",
  ],
  "ATAR": [
    "Functions & Graphs",
    "Calculus — Differentiation",
    "Calculus — Integration",
    "Algebra & Polynomials",
    "Trigonometry",
    "Probability & Statistics",
    "Vectors & Applications",
  ],
  "NAPLAN": [
    "Reading Comprehension",
    "Writing & Text Types",
    "Spelling",
    "Grammar & Punctuation",
    "Number & Algebra",
    "Measurement, Geometry & Statistics",
  ],
  "Bebras": [
    "Algorithms & Sequencing",
    "Data Representation",
    "Pattern Recognition & Abstraction",
    "Decomposition",
    "Logical Deduction",
    "Optimisation & Efficiency",
  ],
  "Kangourou sans frontières (KSF)": [
    "Arithmetic & Number Sense",
    "Geometry & Spatial Reasoning",
    "Algebra & Patterns",
    "Combinatorics & Counting",
    "Logic & Puzzles",
    "Fractions, Ratios & Proportions",
    "Measurement & Time",
  ],
}
